version: '2.1'

services:
  yerbapp-api:
    image: szoomy999/yerbapp-api:latest
    restart: always
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PWD=$POSTGRES_PWD
      - POSTGRES_DB=$POSTGRES_DB
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - ENGINE_API_KEY=$ENGINE_API_KEY
      - SPACES_KEY=$SPACES_KEY
      - SPACES_SECRET=$SPACES_SECRET
      - SPACES_REGION=$SPACES_REGION
      - SPACES_BUCKET=$SPACES_BUCKET
      - SPACES_ENDPOINT=$SPACES_ENDPOINT
    ports:
      - 4000:4000
      - 9229:9229
      - 443:443
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PWD
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
