version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts # the primary container, where your job's commands are run
      - image: postgres:11.5
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
