version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts # the primary container, where your job's commands are run
      - image: postgres:11.5
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
  deploy:
    latest:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -e $DOCKERHUB_EMAIL -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
      - run: docker push name/repo:$CIRCLE_SHA1
      - run: docker push name/repo:latest
      - run: .scripts/deploy.sh
